"""Markdown report renderer."""

from __future__ import annotations


def _label_for(rec: str) -> str:
    return {
        "deploy_with_monitoring": "DEPLOY",
        "deploy_carefully": "DEPLOY CAREFULLY",
        "fix_before_production": "FIX BEFORE PRODUCTION",
        "do_not_deploy": "DO NOT DEPLOY",
    }.get(rec, "UNKNOWN")


def render_markdown(summary: dict, results: list[dict]) -> str:
    lines: list[str] = []
    lines.append(f"# Agent Reliability Report - `{summary['run_id']}`\n")
    lines.append(f"- **Agent:** {summary['agent_name']}")
    lines.append(f"- **Version:** {summary['agent_version']}")
    lines.append(f"- **Suite:** {summary['suite']}")
    lines.append(f"- **Started:** {summary['started_at']}")
    lines.append(f"- **Finished:** {summary['finished_at']}")
    lines.append("")
    rec = summary["deployment_recommendation"]
    lines.append(f"## Deployment: {_label_for(rec)} (`{rec}`)\n")

    lines.append("## Headline Metrics\n")
    lines.append("| Metric | Score |")
    lines.append("|--------|-------|")
    lines.append(f"| Overall | {summary['overall_score']:.0f}/100 |")
    lines.append(f"| Security | {summary['security_score']:.0f}/100 |")
    lines.append(f"| RAG grounding | {summary['rag_score']:.0f}/100 |")
    lines.append(f"| Tool correctness | {summary['tool_score']:.0f}/100 |")
    lines.append(f"| Avg cost | ${summary['avg_cost_usd']:.4f} |")
    p95 = summary.get("p95_latency_ms")
    p95_str = f"{p95 / 1000:.1f}s" if p95 else "n/a"
    lines.append(f"| p95 latency | {p95_str} |")
    lines.append(f"| Pass rate | {summary['passed_scenarios']}/{summary['total_scenarios']} |")
    lines.append("")

    lines.append("## Scenario Results\n")
    lines.append("| Scenario | Status | Score | Failure |")
    lines.append("|----------|--------|-------|---------|")
    for result in results:
        status = "PASS" if result["passed"] else "FAIL"
        score = int(round(result["overall_score"] * 100))
        failure = (result.get("failure_summary") or "").replace("\n", " ").replace("|", "\\|")[:140]
        lines.append(f"| `{result['scenario_id']}` | {status} | {score} | {failure} |")
    lines.append("")

    findings = summary.get("security_findings") or []
    if findings:
        lines.append("## Security Findings\n")
        for finding in findings:
            lines.append(
                f"- **[{finding['severity'].upper()}]** "
                f"`{finding['scenario_id']}` - {finding['finding']}"
            )
        lines.append("")

    lines.append("## Metric Breakdown\n")
    lines.append("| Metric | Avg | Min | Max | Pass rate | Failures |")
    lines.append("|--------|-----|-----|-----|-----------|----------|")
    for metric in summary.get("metric_summaries", []):
        lines.append(
            f"| `{metric['metric_name']}` | {metric['average_score']:.2f} | "
            f"{metric['min_score']:.2f} | {metric['max_score']:.2f} | "
            f"{metric['pass_rate'] * 100:.0f}% | {metric['failure_count']} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [AgentGuard](https://github.com/hamza-safwan/AgentGuard)*")
    return "\n".join(lines)
